version: '3'
services:
  python3:
    restart: always
    build: .
    # dockerfile: ./.devvontainer/dockerfile
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./Gyotaku:/root/Gyotaku